route:
  repeat_interval: 2h
  receiver: group_1
  routes:
    - match:
        alertname: httpd_down
      receiver: group_1

    - match:
        alertname: nginx_down
      receiver: group_1  

receivers:
- name: group_1
  webhook_configs:
  - url: 'http://alertmanager-bot:8080'
    send_resolved: true
      
